


import type { Metadata } from "next";
import { Inter, Cairo, Almarai, Changa } from "next/font/google";
import "./globals.css";
import '../utils/fontAwesome'; // Import the Font Awesome configuration
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "@/src/components/header/Header";
import Footer from "@/src/components/footer/Footer";

//for translation
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';







// export const cairo = Cairo({
//   subsets: ['latin'],
//   weight: ['400', '700'], // Adjust the weights as needed
// });

// Import Google fonts
const inter = Inter({ subsets: ["latin"] });
export const changa = Changa({
  subsets: [],
  weight: ['400'], // Adjust the weights as needed
});

// export const metadata: Metadata = {
//   title: "مركز سرج للدرسات وبالابحاث ",
//   description: "Generated by create next app",
// };

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} dir="rtl">
      <body className={changa.className}>
        <Header />
        <AntdRegistry>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
        </AntdRegistry>
        <Footer />
      </body>
    </html>
  );
}






// import type { Metadata } from "next";
// import { Changa } from "next/font/google";
// import "./globals.css";
// import '../utils/fontAwesome'; // Import the Font Awesome configuration
// import { AntdRegistry } from '@ant-design/nextjs-registry';
// import Header from "@/src/components/header/Header";
// import Footer from "@/src/components/footer/Footer";
// import LocaleProvider from "./LocaleProvider";
// import { getLocale } from "next-intl/server";

// // Import Google fonts
// export const changa = Changa({
//   subsets: [], // Adjust the subsets as needed
//   weight: ['400'], // Adjust the weights as needed
// });

// // Metadata for the page (kept on server)
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const locale = await getLocale();
//   return (
//     <html lang={locale} dir="ltr">
//       <body className={changa.className}>
//         <Header />
//         <AntdRegistry>
//           {/* Move the NextIntl logic to the client-side component */}
//           <LocaleProvider>
//             {children}
//           </LocaleProvider>
//         </AntdRegistry>
//         <Footer />
//       </body>
//     </html>
//   );
// }