import type { Metadata } from "next";
import { Inter, Cairo, Almarai, Changa } from "next/font/google";
import "./globals.css";
import './utils/fontAwesome'; // Import the Font Awesome configuration
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "@/src/components/header/Header";
import Footer from "@/src/components/footer/Footer";









// export const cairo = Cairo({
//   subsets: ['latin'],
//   weight: ['400', '700'], // Adjust the weights as needed
// });

// Import Google fonts
const inter = Inter({ subsets: ["latin"] });
export const changa = Changa({
  subsets: [],
  weight: ['400'], // Adjust the weights as needed
});

// export const metadata: Metadata = {
//   title: "مركز سرج للدرسات وبالابحاث ",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={changa.className}>
        <Header />
          <AntdRegistry>{children}</AntdRegistry>
        <Footer />
      </body>
    </html>
  );
}
